name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: favdev10
          output: dist/github-contribution-grid-snake.svg

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Updated snake animation" || echo "No changes to commit"
          git push
